# -*- coding: utf-8 -*-
"""Linear Model Selection and Regularization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1obrZmLFxvU-yj5ZFGDLHrSZPEAMlrPWx

# Linear Model Selection and Regularization

## Business Understanding

**Sports Analytics**

https://www.transfermarkt.com/

<div>
    <br>
<img src="attachment:MoneyBall.PNG" width = "300" align = "left" />
</div>

### Initial Setups
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

#Read data from csv file
data = pd.read_csv('cs_05.csv')
data.head()

data.shape

"""## Data Understanding

#### 1: Understand data collection process

Hitters data set:

Major League Baseball Data from the 1986 and 1987 seasons

#### 2: Document data set description (meta data)
"""

data.info()

"""0 Name: Player's name

1 AtBat: Number of times at bat in 1986 (numeric)

2 Hits: Number of hits in 1986 (numeric)

3 HmRun: Number of home runs in 1986 (numeric)

4 Runs: Number of runs in 1986 (numeric)

5 RBI: Number of runs batted in in 1986 (numeric)

6 Walks: Number of walks in 1986 (numeric)

7 Years: Number of years in the major leagues (numeric)

8 CAtBat: Number of times at bat during his career (numeric)

9 CHits: Number of hits during his career (numeric)

10 CHmRun: Number of home runs during his career (numeric)

11 CRuns: Number of runs during his career (numeric)

12 CRBI: Number of runs batted in during his career (numeric)

13 CWalks: Number of walks during his career (numeric)

14 League: A factor with levels A and N indicating player's league at the end of 1986 (nominal)

15 Division: A factor with levels E and W indicating player's division at the end of 1986 (nominal)

16 PutOuts: Number of put outs in 1986 (numeric)

17 Assists: Number of assists in 1986 (numeric)

18 Errors: Number of errors in 1986 (numeric)

19 Salary: 1987 annual salary on opening day in thousands of dollars (numeric)

20 NewLeague: A factor with levels A and N indicating player's league at the beginning of 1987 (nominal)

#### 3: Check for missing values
"""

np.sum(data.isnull())

data['is_salary_missed'] = data['Salary'].isnull()
data.head()

#Analysis of MVs
var_ind = list(range(1, 14)) + list(range(16, 19))
plot = plt.figure(figsize = (12, 12))
plot.subplots_adjust(hspace = 0.8, wspace = 0.5)
for i in range(1, 17):
    plt.subplot(4, 4, i)
    plt.boxplot([data.loc[data['is_salary_missed'] == True, data.columns[var_ind[i - 1]]],
                 data.loc[data['is_salary_missed'] == False, data.columns[var_ind[i - 1]]]])
    plt.title(data.columns[var_ind[i - 1]])
    plt.xticks(ticks = [1, 2], labels = ['Missed', 'Available'])

#MVs analysis from categorical variables perspective
for i in ['League', 'Division', 'NewLeague']:
    cross_tab_pct = round(pd.crosstab(data[i],
                                      data['is_salary_missed'],
                                      normalize = 'index'), 2)
    print('--- Cross tab of is_salary_missed vs. ' + i + ' ---')
    print(cross_tab_pct)

#Remove records with MVs
data.dropna(subset = 'Salary', inplace = True)
np.sum(data.isnull())

#Remove is_salary_missed
data.drop(columns = 'is_salary_missed', inplace = True)
data.info()
#Note: sample size is small

"""#### 4: Univariate data analysis"""

#Check if there is duplicate rows
np.sum(data.duplicated())

#Histogram of numeric variables
var_ind = list(range(1, 14)) + list(range(16, 20))
plt.figure(figsize = (12, 6))
plt.subplots_adjust(hspace = 0.5, wspace = 0.5)
for i in range(1, 18):
    plt.subplot(3, 6, i)
    plt.hist(x = data.iloc[: , var_ind[i - 1]],
             alpha = 0.4, color = 'red')
    plt.title(data.columns[var_ind[i - 1]])

#Check for outliers
plt.boxplot(data['Salary'])
plt.show()

#Categorical variables
for i in ['League', 'Division', 'NewLeague']:
    print('--- Frequency Tabel of ' + i + ' ---')
    print(data[i].value_counts())

"""#### 5: Bivariate data analysis"""

#Correlation analysis
corr_table = round(data.iloc[:, var_ind].corr(method = 'pearson'), 2)
corr_table

#Scatter plot
var_ind = list(range(1, 14)) + list(range(16, 19))
plt.figure(figsize = (12, 12))
plt.subplots_adjust(hspace = 0.5, wspace = 0.5)
for i in range(1, 17):
    plt.subplot(4, 4, i)
    plt.scatter(x = data.iloc[: , var_ind[i - 1]], y = data['Salary'], alpha = 0.4, color = 'red')
    plt.title('Salary vs. ' + data.columns[var_ind[i - 1]])

"""## Data Preparation"""

#Remove players' name
data.drop(columns = 'Name', inplace = True)
data.info()

"""## Build Linear Regression Model"""

#Split data into test and train
from sklearn.model_selection import train_test_split
train, test = train_test_split(data,
                               test_size = 0.2,
                               random_state = 1234)
print(train.shape)
print(test.shape)

#Create dummy variables for categorical variables
dummy_vars = pd.get_dummies(train[['League', 'Division', 'NewLeague']])
dummy_vars.info()

#Define base level for each categorical variable
dummy_vars.drop(columns = ['League_A', 'Division_E', 'NewLeague_A'], inplace = True)
dummy_vars.info()

#Define feature matrix
X_ = train.drop(['Salary', 'League', 'Division', 'NewLeague'], axis = 1)
X_train = pd.concat([X_, dummy_vars], axis = 1)
X_train = sm.add_constant(X_train) #adding a constant
X_train.head()

#Define response matrix
y_train = train['Salary']
y_train

"""### Classic Linear Regression"""

#Linear regression - model 1
model_1 = sm.OLS(y_train, X_train).fit()
model_1.summary()

#Function to plot histogram of residuals
def hist_residuals(model, bins = 50):
    #Calculate density
    from scipy import stats
    density = stats.gaussian_kde(model.resid)
    xp = np.linspace(model.resid.min(), model.resid.max(), 100)
    yp = density.pdf(xp)

    #Histogram
    plt.hist(model.resid, bins = bins,
             color = 'red', alpha = 0.7, density = True)
    plt.axvline(model.resid.mean(), color = 'black',
                linewidth = 2, linestyle = '--', label = "Average")
    plt.title('Histogram of Residuals')
    plt.xlabel('Residuals')
    plt.ylabel('Density')
    plt.plot(xp, yp, color = 'black', linewidth = 2)
    plt.legend()

    return plt.show()

#Histogram of residuals - model 1
hist_residuals(model_1)

#QQ-plot - model 1
sm.qqplot(model_1.resid, line = 's')
plt.show()

#Function to plot residuals vs. fitted values
def residuals_fittedvalues_plot(model):
    #Implement Lowess algorithm
    lowess_res = sm.nonparametric.lowess(model.resid, model.fittedvalues)

    #Scatter plot: residuals vs. fitted values
    plt.scatter(x = model.fittedvalues, y = model.resid,
                color = 'red', alpha = 0.7, label = 'data')
    plt.title('Residuals vs. Fitted values')
    plt.xlabel('Fitted Values', fontsize = 12)
    plt.ylabel('Residuals', fontsize = 12)
    plt.grid()

    #Add LOWESS line
    plt.plot(lowess_res[:, 0], lowess_res[:, 1], 'black',
             alpha = 0.8, linewidth = 2, label = 'LOWESS')
    plt.legend()

    #Top three observations with greates absolute value of the residual
    top3 = abs(model.resid).sort_values(ascending = False)[:3]
    for i in top3.index:
        plt.annotate(i, xy = (model.fittedvalues[i], model.resid[i]), color = 'blue')

    return plt.show()

#Scatter plot of residuals vs. fitted values - model 1
residuals_fittedvalues_plot(model_1)

#Function to check Cook's distance
def influencer_detector(model, thershold = 1):

    #create instance of influence
    influence = model.get_influence()

    #Obtain Cook's distance for each observation
    cooks = influence.cooks_distance

    #Check observations w/ Cook's distance greater than thershold
    return np.where(cooks[0] > 1)

#Check Cook's ditance - model 1
influencer_detector(model_1)

#Function to check multicollinearity
from statsmodels.stats.outliers_influence import variance_inflation_factor

def vif(X):
    #Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X, i) for i in range(X.shape[1])]
    return(vif)

#Check multicollinearity for numeric variables
vif(X_train.iloc[:, 1 : 17])
#Note: If VIF > 10 then multicollinearity is high

"""**Conclusion:**

Severe violation of regression assumptions

If select variables based on t-test results, limited number of variables will be selected.

t-test results are not reliable for predictors selection.

Bad model!
"""

#Regression Model based on t-test results
model_1 = sm.OLS(y_train, X_train[['const',
                                   'AtBat',
                                   'Hits',
                                   'Walks',
                                   'PutOuts',
                                   'Division_W']]).fit()
model_1.summary()

#Predict on test - model 1

#Create dummy variables for categorical variables
dummy_vars = pd.get_dummies(test[['League', 'Division', 'NewLeague']])
dummy_vars.drop(columns = ['League_A', 'Division_E', 'NewLeague_A'], inplace = True)

#Define feature matrix
X_ = test.drop(['Salary', 'League', 'Division', 'NewLeague'], axis = 1)
X_test = pd.concat([X_, dummy_vars], axis = 1)
X_test = sm.add_constant(X_test) #adding a constant

#Prediction using model 1
pred_lm = model_1.predict(X_test[['const',
                                  'AtBat',
                                  'Hits',
                                  'Walks',
                                  'PutOuts',
                                  'Division_W']])

pred_lm

#Absolute error
abs_err_lm = abs(test['Salary'] - pred_lm)

#Absolute error mean, median, sd, IQR, max, min
from scipy.stats import iqr
models_comp = pd.DataFrame({'Mean of AbsErrors':    abs_err_lm.mean(),
                            'Median of AbsErrors' : abs_err_lm.median(),
                            'SD of AbsErrors' :     abs_err_lm.std(),
                            'IQR of AbsErrors':     iqr(abs_err_lm),
                            'Min of AbsErrors':     abs_err_lm.min(),
                            'Max of AbsErrors':     abs_err_lm.max()},
                           index = ['LM_t-Test'])
models_comp

#Actual vs. Prediction
plt.scatter(x = test['Salary'], y = pred_lm, c = 'black', alpha = 0.7)
plt.xlabel('Actual')
plt.ylabel('Prediction')
plt.title('Actual vs. Prediction - t-test')

#Add 45 degree line
xp = np.linspace(test['Salary'].min(), test['Salary'].max(), 100)
plt.plot(xp, xp, c = 'red', linewidth = 3)
plt.show()

#Box-Cox transformation
from sklearn.preprocessing import PowerTransformer
boxcox = PowerTransformer(method = 'box-cox')
trans_y_train = boxcox.fit_transform(y_train.values.reshape(-1, 1))

#Linear regression - model 1 with Box-Cox transformation
model_1 = sm.OLS(trans_y_train, X_train).fit()
model_1.summary()

#Histogram of residuals - model 1
hist_residuals(model_1)

#QQ-plot - model 1
sm.qqplot(model_1.resid, line = 's')
plt.show()

#Scatter plot of residuals vs. fitted values - model 1
residuals_fittedvalues_plot(model_1)

"""### Forward Selection"""

#Define function to fit linear regression
def fit_lm(feature_set, y, X):
    reg_model = sm.OLS(y, X[['const'] + list(feature_set)]).fit()
    return {'model': reg_model,
            'r2': reg_model.rsquared,
            'adj_r2': reg_model.rsquared_adj,
            'aic': reg_model.aic,
            'bic': reg_model.bic}

#Define function to do forward selection
def fwd_selection(features, y, X):
    res = []
    #Pull out features still needed to process
    remaining_features = [_ for _ in X.iloc[:, 1:].columns if _ not in features]

    #Fit linear model and save the results
    for f in remaining_features:
        res.append(fit_lm(features + [f], y, X))

    models = pd.DataFrame(res)

    #Choose the model with the highest R squared
    best_model = models.iloc[models['r2'].argmax()]

    #Return the best model
    return best_model

#Forward selection implementation
import time #to measure the processing time
fwd_models = pd.DataFrame(columns = ['model', 'r2', 'adj_r2', 'aic', 'bic'])
start_time = time.time()
features = []
for i in range(1, len(X_train.iloc[:, 1:].columns) + 1):
    fwd_models.loc[i] = fwd_selection(features, trans_y_train, X_train)
    features = fwd_models.loc[i, 'model'].model.exog_names[1:]
end_time = time.time()
print('The Processing time is: ', end_time - start_time, 'seconds')

fwd_models

#Models evaluation
plt.figure(figsize = (12, 6))
plt.subplots_adjust(hspace = 0.5, wspace = 0.2)
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(fwd_models.iloc[:, i], 'r-o', alpha = 0.5)
    plt.title(fwd_models.columns[i])
    plt.xlabel('# of Predictors')
    plt.xticks(range(1, 20))
    plt.ylabel(fwd_models.columns[i])
    plt.grid()

#Liner model with 11 Variables (based on adjusted r2)
fwd_models.loc[11, 'model'].params

#Selected features
fwd_models.loc[11, 'model'].model.exog_names

#Predict on test - model 2
pred_fwd = fwd_models.loc[11, 'model'].predict(X_test[fwd_models.loc[11, 'model'].model.exog_names])
pred_fwd = pd.Series(boxcox.inverse_transform(pred_fwd.values.reshape(-1, 1)).reshape(-1), index = test.index)
pred_fwd

#Absolute error
abs_err_fwd = abs(test['Salary'] - pred_fwd)

#Absolute error mean, median, sd, IQR, max, min
models_comp = pd.concat([models_comp,
                         pd.DataFrame({'Mean of AbsErrors':    abs_err_fwd.mean(),
                                       'Median of AbsErrors' : abs_err_fwd.median(),
                                       'SD of AbsErrors' :     abs_err_fwd.std(),
                                       'IQR of AbsErrors':     iqr(abs_err_fwd),
                                       'Min of AbsErrors':     abs_err_fwd.min(),
                                       'Max of AbsErrors':     abs_err_fwd.max()},
                                      index = ['LM_FWD'])])
models_comp

#Actual vs. Prediction
plt.scatter(x = test['Salary'], y = pred_fwd, c = 'black', alpha = 0.7)
plt.xlabel('Actual')
plt.ylabel('Prediction')
plt.title('Actual vs. Prediction - FWD Selection')

#Add 45 degree line
xp = np.linspace(test['Salary'].min(), test['Salary'].max(), 100)
plt.plot(xp, xp, c = 'red', linewidth = 3)
plt.show()

"""### Backward Elimination"""

#Get all possible combinations - C(n, r)
features = ['CHits', 'Walks', 'HmRun']
import itertools
for i in itertools.combinations(features, len(features) - 1):
    print(i)

#Define function to do backward elimination
def bwd_elimination(features, y, X):
    res = []

    #Fit linear model and save the results
    for f in itertools.combinations(features, len(features) - 1):
        res.append(fit_lm(f, y, X))

    models = pd.DataFrame(res)

    #Choose the model with the highest R squared
    best_model = models.iloc[models['r2'].argmax()]

    #Return the best model
    return best_model

#Backward elimination implementation
bwd_models = pd.DataFrame(columns = ['model', 'r2', 'adj_r2', 'aic', 'bic'])
start_time = time.time()
features = X_train.columns
while(len(features) > 1):
    bwd_models.loc[len(features) - 1] = bwd_elimination(features, trans_y_train, X_train)
    features = bwd_models.loc[len(features) - 1]['model'].model.exog_names[1:]
end_time = time.time()
print('The Processing time is: ', end_time - start_time, 'seconds')

bwd_models

#Models evaluation
plt.figure(figsize = (12, 6))
plt.subplots_adjust(hspace = 0.5, wspace = 0.2)
for i in range(1, 5):
    plt.subplot(2, 2, i)
    plt.plot(bwd_models.iloc[:, i], 'r-o', alpha = 0.5)
    plt.title(bwd_models.columns[i])
    plt.xlabel('# of Predictors')
    plt.xticks(range(1, 20))
    plt.ylabel(bwd_models.columns[i])
    plt.grid()
#Select the best model and predict on test (do it yourself)

"""### Ridge Regression"""

#Scale data before implementing Ridge regression
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

#Implement Ridge regression - model 3
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha = 0.1) #lambda = 0.1 (regularization hyperparameter)
model_3 = ridge_reg.fit(X_train_scaled, trans_y_train)

model_3.coef_

#Grid
lambda_grid = 10 ** np.linspace(3, -3, 100)
lambda_grid

#K-fold cross validation to choose the best model
from sklearn.model_selection import cross_val_score

cv_errors = np.zeros(shape = len(lambda_grid)) #to save cv results

for i in range(len(lambda_grid)):
    ridge_reg = Ridge(alpha = lambda_grid[i])
    scores = cross_val_score(estimator = ridge_reg,
                             X = X_train_scaled,
                             y = trans_y_train,
                             scoring = 'neg_root_mean_squared_error',
                             cv = 5, n_jobs = -1)
    cv_errors[i] = scores.mean()
#To check scoring:
#https://scikit-learn.org/stable/modules/model_evaluation.html

cv_errors

#Best lambda
best_lamda = lambda_grid[np.argmax(cv_errors)]
best_lamda

#Best model coefs:
ridge_reg = Ridge(alpha = best_lamda)
model_3 = ridge_reg.fit(X_train_scaled, trans_y_train)
model_3.coef_

#Predict on test - model 3
#Sacle test data set
X_test_scaled = scaler.transform(X_test)
pred_ridge = model_3.predict(X_test_scaled)
pred_ridge = pd.Series(boxcox.inverse_transform(pred_ridge).reshape(-1), index = test.index)
pred_ridge

#Absolute error
abs_err_ridge = abs(test['Salary'] - pred_ridge)

#Absolute error mean, median, sd, IQR, max, min
models_comp = pd.concat([models_comp,
                         pd.DataFrame({'Mean of AbsErrors':    abs_err_ridge.mean(),
                                       'Median of AbsErrors' : abs_err_ridge.median(),
                                       'SD of AbsErrors' :     abs_err_ridge.std(),
                                       'IQR of AbsErrors':     iqr(abs_err_ridge),
                                       'Min of AbsErrors':     abs_err_ridge.min(),
                                       'Max of AbsErrors':     abs_err_ridge.max()},
                                      index = ['LM_Ridge'])])
models_comp

#Actual vs. Prediction
plt.scatter(x = test['Salary'], y = pred_ridge, c = 'black', alpha = 0.7)
plt.xlabel('Actual')
plt.ylabel('Prediction')
plt.title('Actual vs. Prediction - Ridge Regression')

#Add 45 degree line
xp = np.linspace(test['Salary'].min(), test['Salary'].max(), 100)
plt.plot(xp, xp, c = 'red', linewidth = 3)
plt.show()

"""### LASSO Regression"""

#Implement LASSO regression - model 4
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha = 0.1) #lambda = 0.1 (regularization hyperparameter)
model_4 = lasso_reg.fit(X_train_scaled, trans_y_train)

model_4.coef_

#K-fold cross validation to choose the best model

cv_errors = np.zeros(shape = len(lambda_grid)) #to save cv results

for i in range(len(lambda_grid)):
    lasso_reg = Lasso(alpha = lambda_grid[i])
    scores = cross_val_score(estimator = lasso_reg,
                             X = X_train_scaled,
                             y = trans_y_train,
                             scoring = 'neg_root_mean_squared_error',
                             cv = 5, n_jobs = -1)
    cv_errors[i] = scores.mean()
#To check scoring:
#https://scikit-learn.org/stable/modules/model_evaluation.html

cv_errors

#Best lambda
best_lamda = lambda_grid[np.argmax(cv_errors)]
best_lamda

#Best model coefs:
lasso_reg = Lasso(alpha = best_lamda)
model_4 = lasso_reg.fit(X_train_scaled, trans_y_train)
model_4.coef_

#Predict on test - model 3
pred_lasso = model_4.predict(X_test_scaled)
pred_lasso = pd.Series(boxcox.inverse_transform(pred_lasso.reshape(-1, 1)).reshape(-1), index = test.index)
pred_lasso

#Absolute error
abs_err_lasso = abs(test['Salary'] - pred_lasso)

#Absolute error mean, median, sd, IQR, max, min
models_comp = pd.concat([models_comp,
                         pd.DataFrame({'Mean of AbsErrors':    abs_err_lasso.mean(),
                                       'Median of AbsErrors' : abs_err_lasso.median(),
                                       'SD of AbsErrors' :     abs_err_lasso.std(),
                                       'IQR of AbsErrors':     iqr(abs_err_lasso),
                                       'Min of AbsErrors':     abs_err_lasso.min(),
                                       'Max of AbsErrors':     abs_err_lasso.max()},
                                      index = ['LM_LASSO'])])
models_comp

#Actual vs. Prediction
plt.scatter(x = test['Salary'], y = pred_lasso, c = 'black', alpha = 0.7)
plt.xlabel('Actual')
plt.ylabel('Prediction')
plt.title('Actual vs. Prediction - LASSO Regression')

#Add 45 degree line
xp = np.linspace(test['Salary'].min(), test['Salary'].max(), 100)
plt.plot(xp, xp, c = 'red', linewidth = 3)
plt.show()

"""# End of Code"""